name: CI

on:
  push:
    branches: [ _ ]
  pull_request:
    branches: [ _ ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo mkdir /opt/jvm && curl --proto '=https' --tlsv1.2 -sSfL https://github.com/graalvm/labs-openjdk-17/releases/download/jvmci-21.3-b02/labsjdk-ce-17+35-jvmci-21.3-b02-linux-amd64.tar.gz | sudo tar --strip-components=1 -xzvC /opt/jvm
          export JAVA_HOME=/opt/jvm
          export PATH="/opt/jvm:$PATH"
          git clone --depth 1 https://github.com/graalvm/mx
          export PATH="$PWD/mx:$PATH"
          git clone --depth 1 https://github.com/graalvm/graal.git
          pushd graal/vm
          mx --env ce build
          popd
      - name: ls -R
        run: ls -R
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: graal
          path: graal
