name: CI

on:
  push:
    branches: [ _ ]
  pull_request:
    branches: [ _ ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sudo mkdir /opt/jvm && curl --proto '=https' --tlsv1.2 -sSfL https://github.com/graalvm/labs-openjdk-17/releases/download/jvmci-21.3-b02/labsjdk-ce-17+35-jvmci-21.3-b02-linux-amd64.tar.gz | sudo tar --strip-components=1 -xzvC /opt/jvm
          export JAVA_HOME=/opt/jvm
          export PATH="/opt/jvm:$PATH"
          git clone --depth 1 https://github.com/graalvm/mx
          export PATH="$PWD/mx:$PATH"
          git clone --depth 1 https://github.com/graalvm/graal.git
          pushd graal/vm
          mx --env ce build
          popd
      - name: ls -R
        run: ls -R
      - name: find -name '*.tar*'
        run: find -name '*.tar*'
      - name: find -name '*zip*'
        run: find -name '*zip*'
      - name: Make archives
        run: |
          tar -czvf GRAALVM_CE_JAVA17.tgz -C graal/sdk/mxbuild/linux-amd64/GRAALVM_CE_JAVA17 .
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: GRAALVM_CE_JAVA17.tgz
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: GRAALVM_CE_JAVA17
          path: graal/sdk/mxbuild/linux-amd64/GRAALVM_CE_JAVA17
